Usage
=====

### 1. Data Characteristics ###

This application filters Federal Election Commission (FEC) data for the 2015-2016 election cycle as specified by the user.  Following are the available fields:

 ```
*  1. NAME         - Contributor/Lender/Transfer Name
*  2. CITY         - City/Town
*  3. STATE        - State
   4. EMPLOYER     - Employer
*  5. CMTE_NM      - Committee Name
*  6. PRTY         - Party of D (Democrat) or R (Republican)
*  7. CANDIDATE    - Candidate Last Name
   8. OCCUPATION   - Occupation
*  9. LAST_DATE    - Last Transaction Date
* 10. TOTAL_CONRIB - Total Contributions
* 11. N_CONTRIB    - Number of Contributions

* selected for display at initialization
```

Any of these fields can be selected by checking the corresponding checkbox and all but the last three can be searched by putting a pattern into the corresponding search box.
At initialization, all but EMPLOYER and OCCUPATION are checked and the only search box with a pattern is CANDIDATE with the pattern CLINTON.

The data output is aggregated by NAME, CITY, STATE, EMPLOYER, CMTE_NM, PRTY, and CANDIDATE.  That is, all lines with the same value for these fields will be combined into
one line.  In this case, LAST_DATE will equal the last contribution date (TRANSACTION_DT in the FEC data), TOTAL_CONTRIB will equal the total of the contributions
(TRANSACTION_AMT in the FEC data), N_CONTRIB will equal the number of contributions, and OCCUPATION will equal the maximum occupation (alphabetically).   

The NAME field has been standarized from the original FEC data via the following steps:

1. Remove any trailing MR., MS., or MRS. (with or without the ending period)
2. Remove any trailing middle initial (with or without the ending period)

For example, Michael Bloomberg's name is listed in the FEC data as "BLOOMBERG, MICHAEL", "BLOOMBERG, MICHAEL R", and "BLOOMBERG, MICHAEL R.".  All three are standarized
to "BLOOMBERG, MICHAEL".

### 2. Output from Default Selections ###

Following are the first 33 rows that are displayed as a result of the default selections:

```
[1] "Search CANDIDATE for CLINTON"
[1] ""
[1] "CAMPAIGN FINANCE CONTRIBUTIONS FOR 2015-2016 ELECTION CYCLE THROUGH DECEMBER 2015"
[1] "(grouped by name, city, state, employer, and cmte_nm, sorted by total_contrib)"
[1] ""
[1] "SUM(TOTAL_CONTRIB) = 78,548,042"
[1] "SUM(N_CONTRIB)     = 40,039"
[1] "NUMBER OF ROWS     = 34,619"
[1] ""
                                        NAME               CITY STATE               CMTE_NM PRTY    CANDIDATE  LAST_DATE TOTAL_CONTRIB N_CONTRIB
1                           SANDLER, HERBERT      SAN FRANCISCO    CA PRIORITIES USA ACTION    D      CLINTON 2015-06-24     1,000,000         1
2                          FAIR SHARE ACTION             DENVER    CO PRIORITIES USA ACTION    D      CLINTON 2015-06-29     1,000,000         1
3                              SOROS, GEORGE           NEW YORK    NY PRIORITIES USA ACTION    D      CLINTON 2015-06-25     1,000,000         1
4                            SUSSMAN, DONALD          RYE BROOK    NY PRIORITIES USA ACTION    D      CLINTON 2015-06-30     1,000,000         1
5           UA POLITICAL EDUCATION COMMITTEE          ANNAPOLIS    MD PRIORITIES USA ACTION    D      CLINTON 2015-06-30     1,000,000         2
6                        KATZENBERG, JEFFREY      BEVERLY HILLS    CA PRIORITIES USA ACTION    D      CLINTON 2015-06-26     1,000,000         1
7                          SPIELBERG, STEVEN  PACIFIC PALISADES    CA PRIORITIES USA ACTION    D      CLINTON 2015-06-26     1,000,000         1
8                                SABAN, HAIM        LOS ANGELES    CA PRIORITIES USA ACTION    D      CLINTON 2015-06-29     1,000,000         1
9                              SABAN, CHERYL        LOS ANGELES    CA PRIORITIES USA ACTION    D      CLINTON 2015-06-29     1,000,000         1
10                      SILBERSTEIN, STEPHEN  BELVEDERE TIBURON    CA PRIORITIES USA ACTION    D      CLINTON 2015-06-29       800,000         1
11  PROGRESSIVE WOMEN SILICON VALLEY FEDERAL         SACRAMENTO    CA PRIORITIES USA ACTION    D      CLINTON 2015-06-30       750,000         1
12                              WOODS, LAURE     PORTOLA VALLEY    CA PRIORITIES USA ACTION    D      CLINTON 2015-06-30       750,000         1
13                               SHAW, DAVID           NEW YORK    NY PRIORITIES USA ACTION    D      CLINTON 2015-03-31       750,000         1
14                              LEE, BARBARA          CAMBRIDGE    MA PRIORITIES USA ACTION    D      CLINTON 2015-06-30       716,919         2
15                           ABRAMS, JEFFREY  PACIFIC PALISADES    CA PRIORITIES USA ACTION    D      CLINTON 2015-06-25       500,000         1
16                             HEISING, MARK           ATHERTON    CA PRIORITIES USA ACTION    D      CLINTON 2015-06-17       500,000         1
17                              STRYKER, PAT       FORT COLLINS    CO PRIORITIES USA ACTION    D      CLINTON 2015-05-28       500,000         1
18                         MCGRATH, KATHLEEN  PACIFIC PALISADES    CA PRIORITIES USA ACTION    D      CLINTON 2015-06-25       500,000         1
19                   CLINTON, HILLARY RODHAM           NEW YORK    NY   HILLARY FOR AMERICA    D      CLINTON 2015-05-15       278,810        23
20                          GRIFFIN, KENNETH            CHICAGO    IL              FUTURE45    R ANTI-CLINTON 2015-04-15       250,000         1
21                              SINGER, PAUL           NEW YORK    NY              FUTURE45    R ANTI-CLINTON 2015-04-20       250,000         1
22                               PUGH, JAMES        WINTER PARK    FL PRIORITIES USA ACTION    D      CLINTON 2015-05-12       250,000         1
23                           NATHANSON, MARC      BEVERLY HILLS    CA PRIORITIES USA ACTION    D      CLINTON 2015-06-25       250,000         1
24                             ALTMAN, ROGER           NEW YORK    NY PRIORITIES USA ACTION    D      CLINTON 2015-06-29       250,000         1
25                             TOAN, BARRETT           SANTA FE    NM PRIORITIES USA ACTION    D      CLINTON 2015-06-15       250,000         1
26                           POWERS, WILLIAM        LOS ANGELES    CA              FUTURE45    R ANTI-CLINTON 2015-05-18       100,000         1
27                           GOLDMAN, MARCIA           ATHERTON    CA PRIORITIES USA ACTION    D      CLINTON 2015-05-01       100,000         1
28                             GOLDMAN, JOHN           ATHERTON    CA PRIORITIES USA ACTION    D      CLINTON 2015-05-01       100,000         1
29                           FUKUSHIMA, GLEN         WASHINGTON    DC PRIORITIES USA ACTION    D      CLINTON 2015-06-29       100,000         1
30                     MULLEN, DONALD R. JR.           NEW YORK    NY PRIORITIES USA ACTION    D      CLINTON 2015-06-30       100,000         1
31                              HALE, ROBERT            HINGHAM    MA PRIORITIES USA ACTION    D      CLINTON 2015-03-30       100,000         3
32                              GUZEL, MURAT          BETHLEHEM    PA PRIORITIES USA ACTION    D      CLINTON 2015-06-24        50,000         1
33  INTERNATIONAL ASSOCIATION OF FIRE FIGHTE         WASHINGTON    DC PRIORITIES USA ACTION    D      CLINTON 2015-05-05        50,000         1
```

The rows are always sorted in descending order by TOTAL_CONTRIB.  As can be seen, only rows where the CANDIDATE contains the word CLINTON are
listed.  Note that this includes three rows where CANDIDATE is ANTI-CLINTON.  As to be expected, these three rows have PRTY equal to R,
indicating the Republican Party.

Also, note that the pattern(s) being searched for (CANDIDATE for CLINTON in this case) are listed at the top of the page.  Also, following the title is listed the sums of TOTAL_CONTRIB and N_CONTRIB and the number of rows.  The number of rows and the totals are for all rows that matched the given patterns, not just for the number of rows specified by the Maximum Total Rows option mentioned in section 6.  This option is used just to limit the display and speed up processing. 

### 3. Use of Search Boxes and Regex ###

The searches use the function grep which in turn uses regex expressions as described <A HREF="https://stat.ethz.ch/R-manual/R-devel/library/base/html/regex.html">here</A>.
In regex expressions, the characters ^ and $ indicate the beginning and end of a line, respectively.  Hence, adding a caret ^ immediately before CLINTON in the
CANDIDATE search box searches for CLINTON at the beginning of CANDIDATE.  This causes the three lines with a candidate of ANTI-CLINTON to no longer be listed.
If you then type \^CLINTON into the NAME search box as well, just three lines will be listed.  The first one will be line 19 above which lists the name of the
contributor as CLINTON, HILLARY RODHAM herself.  The line shows that she made 23 contributions to HILLARY FOR AMERICA for a total of $278,810
with the last contribution being made on May 15, 2015.

Following is another example of the use of the search boxes and regex:

```
[1] "Search NAME for BUSH, [BGJ][AE]"
[1] "Search CANDIDATE for BUSH"
[1] ""
[1] "CAMPAIGN FINANCE CONTRIBUTIONS FOR 2015-2016 ELECTION CYCLE THROUGH DECEMBER 2015"
[1] "(grouped by name, city, state, employer, and cmte_nm, sorted by total_contrib)"
[1] ""
                          NAME    CITY STATE           CMTE_NM PRTY CANDIDATE  LAST_DATE TOTAL_CONTRIB N_CONTRIB
1                    BUSH, JEB   MIAMI    FL    JEB 2016, INC.    R      BUSH 2015-06-15       388,715        48
2  BUSH, GEORGE H.W. PRESIDENT HOUSTON    TX RIGHT TO RISE USA    R      BUSH 2015-03-25       125,000         2
3    BUSH, GEORGE W. PRESIDENT MIDLAND    TX RIGHT TO RISE USA    R      BUSH 2015-01-13        95,000         1
4    BUSH, GEORGE W. PRESIDENT MIDLAND    TX    JEB 2016, INC.    R      BUSH 2015-06-22         2,700         1
5 BUSH, GEORGE H. W. PRESIDENT HOUSTON    TX    JEB 2016, INC.    R      BUSH 2015-06-30         2,700         1
6        BUSH, GEORGE PRESCOTT   MIAMI    FL    JEB 2016, INC.    R      BUSH 2015-06-25         2,700         1
7           BUSH, BARBARA P.S. HOUSTON    TX    JEB 2016, INC.    R      BUSH 2015-06-30         2,700         1
```

This shows the contributions by Jeb, George (HW and W), and Barbara Bush to Jeb Bush's campaign.  The [BGJ][AE] in the NAME search box
specifies that the first letter of the first name can be B, G, or J and the second letter can be A or E.  There may be better ways to
do this filtering using regex.  In any case, BUSH, GEORGE PRESCOTT appears to be unrelated to the Bush family and can be filtered out
by putting TX in the STATE search box.

### 4. Use of Sort Radio Buttons ###

Below the search boxes are 4 radio buttons for sorting the data by LAST_DATE in ascending order, LAST_DATE in descending order, TOTAL_CONTRIB in descending order, and N_CONTRIB in descending order.  For equal values, a secondary descending sort is done on TOTAL_CONTRIB.  This sorting helps to examine the data at the maximum (and minimum in the case of LAST_DATE) values of these fields.  For example, selecting to sort by LAST_DATE (ASC) with no values in any search boxes reveals 8 groups of contributions to the STUTZMAN for SENATE committee on 2011-07-14, one contribution on 2013-11-22, and many other contributions starting on the first day of 2014.  Sorting by LAST_DATE (DSC) reveals that there are 73 contribution groups with <NA> (missing data) for LAST_DATE, followed by the following four dates:

```
                                        NAME                   CITY STATE                                  CMTE_NM PRTY        CANDIDATE  LAST_DATE TOTAL_CONTRIB N_CONTRIB
74                         MARTIN, ELIZABETH             PITTSBURGH    PA                                     DSCC    D                  2025-08-05           276         6
75                           BERZOK, MATTHEW               BETHESDA    MD                       KAINE FOR VIRGINIA    D            KAINE 2016-07-26           500         1
76                         CALLAHAN, MICHAEL               MONTREAL    ZZ                AMERICANS SOCIALLY UNITED                       2016-03-31        19,450         1
77                      WILLIAMSON, MARIANNE         WEST HOLLYWOOD    CA         MARIANNE WILLIAMSON FOR CONGRESS            WILLIAMSON 2015-12-31       259,533         6
```

The 73 <NA>'s may indicate that the dates were not entered or were invalid.  The three lines following these, having dates in the future, are likely errors.  The third line for the AMERICANS SOCIALLY UNITED committee is especially interesting.  A story at <A HREF="http://www.publicintegrity.org/2015/09/10/17947/did-shady-pro-bernie-sanders-super-pac-just-dupe-james-bond">this link</A> indicates that this is a "purportedly pro-Bernie Sanders super PAC", "led by Cary Lee Peterson — a man who’s routinely run afoul of creditors and the law".  The article states that "Sanders himself has disvowed super PACs" but that actor Daniel Craig, who plays James Bond, gave nearly $50,000 to this super PAC.  A major problem is that super PACs are largely unregulated by the Federal Election Commission.

In any event, the fourth line and those immediately following it are for the last day of 2015.  However, if the last name of each of the major candidates (CLINTON, O'MALLEY, SANDERS, BUSH, CARSON, CHRISTIE, CRUZ, FIORINA, KASICH, RUBIO, TRUMP, SANTORUM, PAUL, HUCKABEE, PATAKI, GRAHAM, JINDAL, WALKER, and PERRY) are entered into the CANDIDATE search box, it can be seen that all except TRUMP and PAUL currently have no contributions after 2015-9-30.  This appears to be because the file containing contributions by individuals on the <A HREF="http://www.fec.gov/finance/disclosure/ftpdet.shtml#a2015_2016">FEC site</A> is dated 31-JAN-2016 at the time that I write this and much of the individual data through the end of 2015, which is due on 31-JAN-2016, is likely still being cleaned and processed and has not yet been uploaded to the site.  In any case, this shows another useful function of the sort radio buttons.

### 5. Use of Checkboxes ###

Following is a search for the contributions of Larry Ellison, the Chairman and CTO of Oracle using the default checkbox selections:

```
[1] "Search NAME for ELLISON, LA"
[1] ""
[1] "CAMPAIGN FINANCE CONTRIBUTIONS FOR 2015-2016 ELECTION CYCLE THROUGH DECEMBER 2015"
[1] "(grouped by name, city, state, employer, and cmte_nm, sorted by total_contrib)"
[1] ""
               NAME         CITY STATE                    CMTE_NM PRTY CANDIDATE  LAST_DATE TOTAL_CONTRIB N_CONTRIB
1 ELLISON, LAWRENCE WALNUT CREEK    CA CONSERVATIVE SOLUTIONS PAC    R     RUBIO 2015-06-24     3,000,000         2
2 ELLISON, LAWRENCE WALNUT CREEK    CA    HATCH VICTORY COMMITTEE                2015-07-20       143,800         2
3 ELLISON, LAWRENCE WALNUT CREEK    CA  MARCO RUBIO FOR PRESIDENT    R     RUBIO 2015-06-30        10,800         6
4 ELLISON, LAWRENCE WALNUT CREEK    CA     FRIENDS FOR HARRY REID    D      REID 2015-05-01         2,400         1
5 ELLISON, LAWRENCE WALNUT CREEK    CA        CANTOR FOR CONGRESS    R    CANTOR 2015-06-08           360         1
```

Following is the same search with EMPLOYER and OCCUPATION also checked:

```
[1] "Search NAME for ELLISON, LA"
[1] ""
[1] "CAMPAIGN FINANCE CONTRIBUTIONS FOR 2015-2016 ELECTION CYCLE THROUGH DECEMBER 2015"
[1] "(grouped by name, city, state, employer, and cmte_nm, sorted by total_contrib)"
[1] ""
               NAME         CITY STATE           EMPLOYER                    CMTE_NM PRTY CANDIDATE                        OCCUPATION  LAST_DATE TOTAL_CONTRIB N_CONTRIB
1 ELLISON, LAWRENCE WALNUT CREEK    CA             ORACLE CONSERVATIVE SOLUTIONS PAC    R     RUBIO CHAIRMAN/CHIEF TECHNOLOGY OFFICER 2015-06-24     3,000,000         2
2 ELLISON, LAWRENCE WALNUT CREEK    CA ORACLE CORPORATION    HATCH VICTORY COMMITTEE                  EXECUTIVE CHAIRMAN OF THE BOARD 2015-07-20       143,800         2
3 ELLISON, LAWRENCE WALNUT CREEK    CA             ORACLE  MARCO RUBIO FOR PRESIDENT    R     RUBIO   EXECUTIVE CHAIRMAN OF THE BOARD 2015-06-30        10,800         6
4 ELLISON, LAWRENCE WALNUT CREEK    CA                        FRIENDS FOR HARRY REID    D      REID                                   2015-05-01         2,400         1
5 ELLISON, LAWRENCE WALNUT CREEK    CA                           CANTOR FOR CONGRESS    R    CANTOR                                   2015-06-08           360         1
```

As can be seen, there is no requirement that EMPLOYER or OCCUPATION be standarized in FEC data.  In fact, setting ORACLE in the EMPLOYER search box would have caused
the last two lines to have been missed.

By the way, the above data shows a weakness in the data.  To my knowledge, the FEC data lists the party and candidate for the primary committee of each candidate but not for the so-called super PACs.  For super PACs, this data is obtained from a list compiled by OpenSecrets.org at <A HREF="https://www.opensecrets.org/pacs/superpacs.php?cycle=2016">this link</A>.  However, the Hatch Victory Committee is not listed here, possibly because it is a joint fundraising committee whose funds do not go only to Senator Hatch.  However, <A HREF="http://www.opensecrets.org/jfc/summary.php?id=C00542886">this link</A> shows that the funds all go to Republicans.

### 6. Use of Other Options ###

The remaining options are the Maximum Column Width, Maximum Total Width, and Maximum Total Rows.  The following shows the effect of a Maximum Column Width of 10 on the prior example:

```
[1] "Search NAME for ELLISON, LA"
[1] ""
[1] "CAMPAIGN FINANCE CONTRIBUTIONS FOR 2015-2016 ELECTION CYCLE THROUGH DECEMBER 2015"
[1] "(grouped by name, city, state, employer, and cmte_nm, sorted by total_contrib)"
[1] ""
        NAME       CITY STATE   EMPLOYER    CMTE_NM PRTY CANDIDATE OCCUPATION  LAST_DATE TOTAL_CONTRIB N_CONTRIB
1 ELLISON, L WALNUT CRE    CA     ORACLE CONSERVATI    R     RUBIO CHAIRMAN/C 2015-06-24     3,000,000         2
2 ELLISON, L WALNUT CRE    CA ORACLE COR HATCH VICT                EXECUTIVE  2015-07-20       143,800         2
3 ELLISON, L WALNUT CRE    CA     ORACLE MARCO RUBI    R     RUBIO EXECUTIVE  2015-06-30        10,800         6
4 ELLISON, L WALNUT CRE    CA            FRIENDS FO    D      REID            2015-05-01         2,400         1
5 ELLISON, L WALNUT CRE    CA            CANTOR FOR    R    CANTOR            2015-06-08           360         1
```

As can be seen, NAME, CITY, EMPLOYER, CMTE_NM, and OCCUPATION were all truncated to a maximum of 10 characters.  None of the other columns are ever truncated.

The following shows the effect of a Maximum Total Width of 100 on the above example (with Maximum Column Width set back to 40):

```
[1] "Search NAME for ELLISON, LA"
[1] ""
[1] "CAMPAIGN FINANCE CONTRIBUTIONS FOR 2015-2016 ELECTION CYCLE THROUGH DECEMBER 2015"
[1] "(grouped by name, city, state, employer, and cmte_nm, sorted by total_contrib)"
[1] ""
               NAME         CITY STATE           EMPLOYER                    CMTE_NM PRTY CANDIDATE
1 ELLISON, LAWRENCE WALNUT CREEK    CA             ORACLE CONSERVATIVE SOLUTIONS PAC    R     RUBIO
2 ELLISON, LAWRENCE WALNUT CREEK    CA ORACLE CORPORATION    HATCH VICTORY COMMITTEE               
3 ELLISON, LAWRENCE WALNUT CREEK    CA             ORACLE  MARCO RUBIO FOR PRESIDENT    R     RUBIO
4 ELLISON, LAWRENCE WALNUT CREEK    CA                        FRIENDS FOR HARRY REID    D      REID
5 ELLISON, LAWRENCE WALNUT CREEK    CA                           CANTOR FOR CONGRESS    R    CANTOR
                         OCCUPATION  LAST_DATE TOTAL_CONTRIB N_CONTRIB
1 CHAIRMAN/CHIEF TECHNOLOGY OFFICER 2015-06-24     3,000,000         2
2   EXECUTIVE CHAIRMAN OF THE BOARD 2015-07-20       143,800         2
3   EXECUTIVE CHAIRMAN OF THE BOARD 2015-06-30        10,800         6
4                                   2015-05-01         2,400         1
5                                   2015-06-08           360         1
```

As can be seen, the output is wrapped so that it does not surpass 100 characters and the row number is repeated.

Finally, the following shows the effect of a Maximum Total Rows of 4 (with Maximum Total Width reset to 240):

```
[1] "Search NAME for ELLISON, LA"
[1] ""
[1] "CAMPAIGN FINANCE CONTRIBUTIONS FOR 2015-2016 ELECTION CYCLE THROUGH DECEMBER 2015"
[1] "(grouped by name, city, state, employer, and cmte_nm, sorted by total_contrib)"
[1] ""
               NAME         CITY STATE           EMPLOYER                    CMTE_NM PRTY CANDIDATE                        OCCUPATION  LAST_DATE TOTAL_CONTRIB N_CONTRIB
1 ELLISON, LAWRENCE WALNUT CREEK    CA             ORACLE CONSERVATIVE SOLUTIONS PAC    R     RUBIO CHAIRMAN/CHIEF TECHNOLOGY OFFICER 2015-06-24     3,000,000         2
2 ELLISON, LAWRENCE WALNUT CREEK    CA ORACLE CORPORATION    HATCH VICTORY COMMITTEE                  EXECUTIVE CHAIRMAN OF THE BOARD 2015-07-20       143,800         2
3 ELLISON, LAWRENCE WALNUT CREEK    CA             ORACLE  MARCO RUBIO FOR PRESIDENT    R     RUBIO   EXECUTIVE CHAIRMAN OF THE BOARD 2015-06-30        10,800         6
4 ELLISON, LAWRENCE WALNUT CREEK    CA                        FRIENDS FOR HARRY REID    D      REID                                   2015-05-01         2,400         1
```

As can be seen, the number of rows is simply truncated to 4.

### 7. Other Example Queries ###

The following shows the contributions of Donald Trump in the 2015-2016 campaign cycle through December 2015:

```
[1] "Search NAME for TRUMP, DO"
[1] ""
[1] "CAMPAIGN FINANCE CONTRIBUTIONS FOR 2015-2016 ELECTION CYCLE THROUGH DECEMBER 2015"
[1] "(grouped by name, city, state, employer, and cmte_nm, sorted by total_contrib)"
[1] ""
[1] 9
[1] "900"
           NAME     CITY STATE                                  CMTE_NM PRTY CANDIDATE  LAST_DATE TOTAL_CONTRIB N_CONTRIB
1 TRUMP, DONALD NEW YORK    NY      DONALD J. TRUMP FOR PRESIDENT, INC.    R     TRUMP 2015-09-24       104,819        23
2 TRUMP, DONALD NEW YORK    NY                 REPUBLICAN PARTY OF IOWA    R           2015-05-28         9,000         1
3 TRUMP, DONALD NEW YORK    NY                     DONOVAN FOR CONGRESS    R   DONOVAN 2015-05-15         5,400         2
4 TRUMP, DONALD NEW YORK    NY                     DONOVAN FOR CONGRESS    D   DONOVAN 2015-05-15         5,400         2
5 TRUMP, DONALD NEW YORK    NY NEW HAMPSHIRE REPUBLICAN STATE COMMITTEE    R           2015-04-30         5,000         1
6 TRUMP, DONALD NEW YORK    NY          SOUTH CAROLINA REPUBLICAN PARTY    R           2015-04-28         5,000         1
7 TRUMP, DONALD NEW YORK    NY                FRIENDS OF DAVE BRAT INC.    R      BRAT 2015-04-15         2,600         1
8 TRUMP, DONALD NEW YORK    NY                        HELLER FOR SENATE    R    HELLER 2015-03-31         2,000         1
9 TRUMP, DONALD NEW YORK    NY       TEXANS FOR SENATOR JOHN CORNYN INC    R    CORNYN 2015-06-11         1,000         1
```

As in the case of Jeb Bush above, Trump has made numerous contributions to his own committee.  One item of interest is that he also made contributions to the
Republican party of Iowa, New Hampshire, and South Carolina, the first three primaries for Republicans.
